### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by ZzzDave** [AndrewFM/VoezEditor#1]
Hey I would just like to know if you want to continue working on the project or if it is dead because I think you deleted the server (or I got banned and I don't know) and there is no new releas

**Comment by AndrewFM** [comment]
The project is still alive. The server did get deleted though (It wasn't my server, and the dude who did own it just decided to randomly delete the server without warning for some reason... really lame). I put together my own VOEZ Editor Discord server last night, you can rejoin here: https://discord.gg/3drjmVg

**Comment by ZzzDave** [comment]
Alright thanks for letting me know (you should also change the invite on gbatemp if you didn’t yet ;) I didn’t checked)
