### ISSUE TITLE
Crash when reaching end of song

### ISSUE THREAD

**Issue by Sickliff** [AndrewFM/VoezEditor#2]
At the end of a song, the editor does not automatically pause. If you don't pause manually, the program will crash.

[error.log](https://github.com/AndrewFM/VoezEditor/files/6549690/error.log)
[output_log.txt](https://github.com/AndrewFM/VoezEditor/files/6549691/output_log.txt)
[crash.dmp.zip](https://github.com/AndrewFM/VoezEditor/files/6549692/crash.dmp.zip)

**Comment by AndrewFM** [comment]
From an initial test, it seems like this is only happening when the song is a WAV file. For now until this is fixed, you can try converting your song file to OGG format.
